# Generated by Django 6.0.5 on 2026-07-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='participation',
            new_name='behavior',
        ),
    ]
