# Generated by Django 6.0.5 on 2026-07-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_email_notifications_alter_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temporary_passwords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
