# Generated by Django 6.0.5 on 2026-07-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_temporary_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='program',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='room',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='schedule',
        ),
    ]
