# Generated by Django 6.0.5 on 2026-07-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_classroom_class_name_remove_classroom_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
