# Generated by Django 6.0.5 on 2026-07-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_classroom_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='hw_prep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='hw_prep_comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='lesson_prog',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='lesson_prog_comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='next_lesson',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
