# Generated by Django 6.0.5 on 2026-07-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_log_hw_prep_log_hw_prep_comments_log_lesson_prog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='hw_prep',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='lesson_prog',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
